ipaserver_base_command: ipa-server-install -U 
ipaserver_hbac_allow: True
ipaserver_idstart: 5000
ipaserver_idmax: False
ipaserver_packages:
  - bind
  - bind-pkcs11
  - bind-pkcs11-utils
  - bind-dyndb-ldap
  - ipa-server-dns
  - ipa-server
  - ipa-client
  - ipa-admintools
ipaserver_setup_ntp: True
